### PR TITLE
Add PHPStan to CI

### PR DESCRIPTION
**Pull request by szepeviktor**
After #4

### CODE REVIEW

**Comment by szepeviktor** [comment]
@matthiasnoback There are two things on my wish list.

1. You read out loud your book to me.
2. I receive a printed copy.

**Comment by matthiasnoback** [comment]
Cool, can you rebase this?

**Comment by szepeviktor** [comment]
Done 🍏

**Comment by matthiasnoback** [comment]
Thanks a lot!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
