### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by szepeviktor**
Looks very nice 🤩 

kép

### CODE REVIEW

**Comment by szepeviktor** [comment]
- src and tests were lifted to root
- resources were moved to .github

**Comment by matthiasnoback** [comment]
I appreciate your big effort here but I don't want to restructure. The current structure is the one we follow in the book, so it doesn't make sense to change it. Maybe you can propose changes in Issues first?

**Comment by szepeviktor** [comment]
All right.
I like to contribute even when my PR gets closed.

**Comment by szepeviktor** [comment]
This directory structure is like ancient PSR-0 😿 

kép

**Comment by matthiasnoback** [comment]
It's okay, I just want to make sure you don't spend too much time, I always hate it to close PRs.

**Pull request closed without merging**
